[project]
name = "price-volume-mix"
version = "0.1.0"
description = "Price volume mix analysis in Python"
authors = ["Aurimas Racas <mail@aurimas.eu>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
python = ">=3.12.1,<3.13"
polars = ">=0.20.3,<0.21"
altair = ">=5.2.0,<5.3"
mypy = ">=1.8.0,<1.9"
ruff = ">=0.1.11,<0.2"
