[project]
name = "price-volume-mix"
version = "0.1.0"
description = "Price volume mix analysis in Python"
authors = ["Aurimas Racas <mail@aurimas.eu>"]
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]
license = "MIT"
repository = "https://github.com/kamicollo/price-volume-mix"

[tasks]

[host-dependencies]
python = ">=3.12.1,<3.13"

[dependencies]
polars = ">=0.20.3,<0.21"
altair = ">=5.2.0,<5.3"
mypy = ">=1.8.0,<1.9"
ruff = ">=0.1.11,<0.2"
ipykernel = ">=6.28.0,<6.29"
tabulate = ">=0.9.0,<0.10"
numpy = ">=1.26.3,<1.27"
