project:
  type: book
  preview:
    port: 4200
    browser: false

metadata-files:
  - _website.yml
  - _book.yml

format:
  html:
    theme: cosmo

notebook-links: true
notebook-view:
  - notebook: notebooks/intro_to_price_volume_analysis.ipynb
    title: "Plots and Computations"
    url: https://colab.research.google.com/drive/12GsIPQ644SI4vkEEHiZn-Qqfbr-bD1__



